// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPYZKnT1xfjFWnmLXW6vkiRvR0uHPDHM',
    appId: '1:506436497941:android:5d9bc26d5c496916fad41c',
    messagingSenderId: '506436497941',
    projectId: 'rfg-app-f9a4b',
    databaseURL: 'https://rfg-app-f9a4b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rfg-app-f9a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhY1uEjMvLHyuL4bVFQ5rXoD0H2LtHir4',
    appId: '1:506436497941:ios:cc9d8cf155d98229fad41c',
    messagingSenderId: '506436497941',
    projectId: 'rfg-app-f9a4b',
    databaseURL: 'https://rfg-app-f9a4b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rfg-app-f9a4b.appspot.com',
    androidClientId: '506436497941-3d85202loace1ibo1aqavtlq720vosoj.apps.googleusercontent.com',
    iosClientId: '506436497941-7hv20j6c53k7qnkfm9r02j4vmhlulmmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rfgApp',
  );
}
